### ISSUE TITLE
Orb is stated to be unused

### ISSUE THREAD

**Issue by BrentWilkins** [CircleCI-Public/circleci-yaml-language-server#265]
I roughly copy-pasted the following code from [this example](https://circleci.com/developer/orbs/orb/circleci/aws-ecr#usage-build_and_push_image_w_registry_login).

```yaml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1
  aws-ecr: circleci/aws-ecr@9.0
jobs:
  build-test-then-push-with-buildx:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - aws-ecr/build_and_push_image:
          attach_workspace: true
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::123456789012
          create_repo: true
          dockerfile: Dockerfile
          path: workspace
          platform: linux/amd64
          push_image: false
          region: us-west-2
          repo: my-sample-repo
          tag: sampleTag
          workspace_root: .

workflows:
  build-and-test:
    jobs:
      - build-test-then-push-with-buildx
```

`aws-cli: circleci/aws-cli@4.1` has the yellow squiggly underline. It expands to this:

> Orb is unused cci-language-server
> [https://circleci.com/docs/creating-orbs#semantic-versioning-in-orbs](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
> 
> An orb to depend on and its semver range, or volatile for the most recent release.
> 
> CircleCI config.yml
> [https://circleci.com/docs/creating-orbs#semantic-versioning-in-orbs](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
> 
> An orb to depend on and its semver range, or volatile for the most recent release.
> 
> Source: [circleciconfig.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

What is it called when we use it in the auth section below that? In my actual project I don't get the unused error, but I get an undefined error where I use it.
