### ISSUE TITLE
Support for expression-based job filters

### ISSUE THREAD

**Issue by bborysenko** [CircleCI-Public/circleci-yaml-language-server#335]
It appears that the language server does not currently support [expression-based job filters](https://circleci.com/docs/configuration-reference/#expression-based-job-filters) added [recently](https://circleci.canny.io/cloud-feature-requests/p/support-for-conditional-jobs-in-workflows). Because of this, there is no way to check the pipeline before committing the configuration to the repository. And most likely, adding expression-based filters will make working with CircleCI in VSCode completely impossible.

![Image](https://github.com/user-attachments/assets/acd779f8-dc69-4361-94c8-03bef1d2cd12)

## Steps to reproduce

Add expression-based filters within a workflow, like in the example below:

```yaml
workflows:
  <workflow_name>:
    jobs:
      - <job_name>:
           filters: pipeline.git.branch ==  "main"
```

However, VSCode displays `Invalid type. Expected: object, given: string` error.

## Debug info

```
OS:+Darwin+(darwin+arm64)+24.5.0  
App:+Visual+Studio+Code+1.100.2+desktop  
CircleCI+extension:+v2.10.1+(ui)  
Language+server:+v0.14.0
```
